version: '3.8'

services:
  web:
    build: .
    container_name: django_web
    command: >
      ./wait-for-it.sh db:5432 --
      sh -c "python manage.py collectstatic --noinput &&
             daphne -b 0.0.0.0 -p 8000 izin_takip.asgi:application"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    depends_on:
      - redis
      - db
    environment:
      DJANGO_SETTINGS_MODULE: izin_takip.settings
    # Removed 'env_file'

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A izin_takip worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      DJANGO_SETTINGS_MODULE: izin_takip.settings

  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: postgres:13-alpine
    container_name: postgres_db
    ports:
      - "5433:5432" 
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static_volume:
