# Generated by Django 4.2.16 on 2024-11-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_management", "0002_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="total_working_hours",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
