# Generated by Django 4.2.16 on 2024-11-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leave_management", "0005_alter_attendance_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together=set(),
        ),
    ]
